<a href="https://colab.research.google.com/github/pathader/Python-Data-course/blob/main/Copy_of_Data_retrieval_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data retrieval
---

Examples of data being retrieved from a range of sources

## From a web page
---

The code below reads all the data tables from the Wikipedia page on Glasgow.  The 8th table on the page shows population data over a period of centuries.

The code reads the data from the page into a list of datatables.  The index [7] is used to access the 8th table in the list.  Change the index to see other data tables.  Use len(datatables) to find out how many tables are in the list.

In [12]:
import pandas as pd
datatables = pd.read_html('https://en.wikipedia.org/wiki/Glasgow#Climate')
df = datatables[7]  #Glasgow population data

length=len(datatables)
print("length", length)
df

length 23

,Year[98],Population,Area (km2),Density (inhabitants/km2),Area changes
0,1300,1500,-[99],–,Initial
1,1600,7000,–,–,Unknown
2,1791,66000,7.16,9217,Anderson to James Street/West Nile Street to C...
3,1831,202426,8.83,22924,Necropolis and Blythswood
4,1846,280000,23.44,11945,Burghs of Anderston and Calton/Barony of Gorbals
5,1872,494824,24.42,20263,"Districts of Keppochhill, Alexandra Parade and..."
6,1891,658073,48.00,13709,"Burghs of Govanhill, Crosshill, Pollokshields,..."
7,1901,761712,51.35,14833,Bellahouston Park and Craigton. Districts of B...
8,1912,800000,77.63,10305,"Burghs of Govan, Partick, Pollokshaws. Distric..."
9,1921,1034174,77.63,13321,No change
10,1926,1090380,119.42,9130,"Districts of Lambhill, Millerston, Aikenhead, ..."
11,1938,1127825,160.77,7015,"Districts of Balmuildy, Auchinairn, Cardowan, ..."
12,1946,1050000,160.77,6531,No change
13,1951,1089555,160.77,6777,No change
14,1961,1055017,160.77,6562,No change
15,1971,897485,160.77,5582,No change
16,1981,774068,202.35,3825,"Burghs of Rutherglen, Cambuslang, Mount Vernon..."
17,1991,688600,202.67,3397,Minor boundary change
18,2001,586710,177.30,3309,Rutherglen and Cambuslang transferred to South...
19,2011,599650,174.70,3432,Minor boundary change

## From a csv file hosted on Github.com
---

The code below reads the data table stored in a Comma Separated Values file (this is a text file containing rows of data with each column within the row separated from the next column by a comma).  

If you were using Jupyter Notebooks on your device, the url could be replaced with the path to the CSV file.

In [13]:
import pandas as pd
url = "https://raw.githubusercontent.com/futureCodersSE/working-with-data/main/Data%20sets/Paisley-Weather-Data.csv"
df = pd.read_csv(url)
df

,yyyy,mm,tmax (degC),tmin (degC),af (days),rain (mm),sun (hours),status
0,1959,1,4,-2,25,40.9,54.1,NaN
1,1959,2,6.6,2.1,10,41.8,17.8,NaN
2,1959,3,10.6,4.2,0,50.9,85.7,NaN
3,1959,4,13,5.2,0,76.3,125.1,NaN
4,1959,5,18.1,7.9,0,24,222,NaN
...,...,...,...,...,...,...,...,...
741,2020,10,12.9*,7.1*,0*,185.3*,76.8*,Provisional
742,2020,11,10.6*,6.0*,0*,142.4*,29.3*,Provisional
743,2020,12,6.9*,2.6*,8*,131.0*,31.6*,Provisional
744,2021,1,4.9*,-0.2*,14*,132.2*,51.0*,Provisional
745,2021,2,7.0*,2.3*,8*,144.3*,58.8*,Provisional

## From an Excel file hosted on Github.com
---

The code below reads the data table from a sheet in an Excel file.  If you don't specify a sheet then it will assume that you want to read the data from the first sheet in the Excel workbook (sheet_name = 0).  If you don't know the sheet name but know it is the second sheet, you can use sheet_name = 1, or 2 for the third sheet, etc.

If you were using Jupyter Notebooks on your device, the url could be replace with the path to the Excel file.

In [15]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name="Industry Migration")
df

,country_code,country_name,wb_income,wb_region,isic_section_index,isic_section_name,industry_id,industry_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
0,ae,United Arab Emirates,High income,Middle East & North Africa,C,Manufacturing,1,Defense & Space,378.74,127.94,8.20,68.51,49.55
1,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,3,Computer Hardware,100.97,358.14,112.98,149.57,182.22
2,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,4,Computer Software,1079.36,848.15,596.48,409.18,407.41
3,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,5,Computer Networking,401.46,447.39,163.99,236.69,188.07
4,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,6,Internet,1840.33,1368.42,877.71,852.39,519.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5290,zw,Zimbabwe,Low income,Sub-Saharan Africa,B,Mining and quarrying,56,Mining & Metals,257.36,187.70,-17.45,70.60,-18.30
5291,zw,Zimbabwe,Low income,Sub-Saharan Africa,P,Education,68,Higher Education,190.84,50.76,-68.74,-234.59,-304.36
5292,zw,Zimbabwe,Low income,Sub-Saharan Africa,O,Public administration and defence; compulsory ...,74,International Affairs,25.23,-46.12,214.29,311.03,-55.88
5293,zw,Zimbabwe,Low income,Sub-Saharan Africa,J,Information and communication,96,Information Technology & Services,46.65,35.93,-142.64,-108.16,-213.82
5294,zw,Zimbabwe,Low income,Sub-Saharan Africa,S,Other service activities,100,Non-Profit Organization Management,133.56,88.48,6.96,-39.32,-92.51

## From an API which delivers the data in JSON format
---

The code below requests the data from the url.  This is a bit more tricky than the other ways to get the data as how you access the data will depend on how it is organised.

In this example, the data is returned as a dictionary, which will have the key 'data' against which the actual data is stored.  In the example, the data has been taken from the 'data' key/value pair and is stored in json_data.

Again, in this example, the json_data is a list of json_objects but it only has one object in the list.  Try adding the line `print(json_data)` to see this.  

data_table is the first object in the json_data list.  Try adding the line `print(data_table)` to see this.

In this example, the data table object has three keys, 'to', 'from' and 'regions'.  The 'regions' value is the data we want to use in our dataframe, so we normalize this json data into a pandas dataframe (df), which you can see as the output.  

Each API is likely to deliver its data in a different format and so you will need to be happy to read the documentation and to inspect the data to see what keys and indexes you need to access.

For information on the format of the data, see https://carbon-intensity.github.io/api-definitions/#regional

In [ ]:
import pandas as pd
import requests

url = "https://api.carbonintensity.org.uk/regional"
json_data = requests.get(url).json()['data']
data_table = json_data[0]
df = pd.json_normalize(data_table['regions'])
df

## Exercise - upload a CSV file to your own Github account and write Python code to load it into a dataframe
---

1.  Download the CSV file at this link to your downloads folder on your computer: https://drive.google.com/file/d/15vDkpCKqlRHQt8f8VHER97fIqZytIAtu/view?usp=sharing

2.  Create a folder called 'Data Sets' and move the CSV file into the Data Sets folder.

3.  Log in to your Github account and navigate to the repository where you are uploading all your Colab Worksheets

4.  Click on the Add File button  
![Add file to Github](https://drive.google.com/uc?id=1szQpVcLg56yPPJc6z4wvK9mCGzSNSa5q)  Select *Upload Files* and then drag the Data Sets folder onto the page (drag the folder rather than the files in it).  Once the folder has uploaded, you will need to commit the changes.  Scroll down the page to see the Commit Changes button.  Before you commit, you can add an extended description *e.g. New folder to store data sets.*

5.  Click to open the Data Sets folder in your Github repository.  Then click to select the file `housing_in_london_yearly_variables.csv`.  You will need a link to the 'raw' data version of this file.  
![Get raw data](https://drive.google.com/uc?id=1_B9_1YK35eRpXp5kN2zBZRu0m_CIBn5i)  
Click on 'raw', you will see just the data shown in the page.  Select the URL for this page and copy it.  **This is the link you will need.**  

You can now refer to the section above 'From a csv file hosted on Github.com' and create a dataframe from your newly uploaded CSV file.

### Note:
for future data set uploads you will just need to navigate to the Data Sets folder in your Github repository and click on Add File there.  You can then just upload the file and it will sit in the Data Sets folder.

In [16]:
import pandas as pd
url = "https://raw.githubusercontent.com/pathader/Python-Data-course/main/Data%20Sets/housing_in_london_yearly_variables.csv"
df = pd.read_csv(url)
df

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
0,E09000001,city of london,1999-12-01,33020.0,NaN,48922,0,6581.0,NaN,NaN,NaN,1
1,E09000002,barking and dagenham,1999-12-01,21480.0,NaN,23620,3,162444.0,NaN,NaN,NaN,1
2,E09000003,barnet,1999-12-01,19568.0,NaN,23128,8,313469.0,NaN,NaN,NaN,1
3,E09000004,bexley,1999-12-01,18621.0,NaN,21386,18,217458.0,NaN,NaN,NaN,1
4,E09000005,brent,1999-12-01,18532.0,NaN,20911,6,260317.0,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1066,K03000001,great britain,2019-12-01,30446.0,NaN,37603,NaN,NaN,NaN,NaN,NaN,0
1067,K04000001,england and wales,2019-12-01,30500.0,NaN,37865,NaN,NaN,NaN,NaN,NaN,0
1068,N92000002,northern ireland,2019-12-01,27434.0,NaN,32083,NaN,NaN,NaN,NaN,NaN,0
1069,S92000003,scotland,2019-12-01,30000.0,NaN,34916,NaN,NaN,NaN,NaN,NaN,0
1070,W92000004,wales,2019-12-01,27500.0,NaN,31251,NaN,NaN,NaN,NaN,NaN,0